services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ndis_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "${SA_PASSWORD}", "-Q", "SELECT 1", "-C"]
      interval: 10s
      timeout: 5s
      retries: 12

  rabbitmq:
    image: rabbitmq:3-management
    container_name: ndis_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"

  user-api:
    build:
      context: .
      dockerfile: NDIS.User.API/Dockerfile
    container_name: ndis_user_api
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    environment:
      ASPNETCORE_URLS: "http://+:5000"
      ASPNETCORE_ENVIRONMENT: "Development"

      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=UserDb;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=True;"
      Jwt__Key: ${JWT_KEY}
      Jwt__Issuer: "NDISS.User.API"
      Jwt__Audience: "NDISS.User.API"

      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: ${RABBITMQ_USERNAME}
      RabbitMQ__Password: ${RABBITMQ_PASSWORD}
      RabbitMQ__VirtualHost: "/"
      RabbitMQ__Port: "5672"
    ports:
      - "5000:5000"
